#!/usr/bin/env bash
set -e

username="${1:-default_username}"
failure_count="${2:-3}"

for i in $(seq 1 $failure_count)
do {
  current_time="${3:-$(gdate -u +%FT%T.%3NZ)}"
  user_overrides=$(jq -n --arg name "$username" --arg time "$current_time" '{"@timestamp": $time, "user": {"name": $name}}')
  failure_overrides=$(jq -n '{"event": {"type": ["authentication_failure", "info"], "outcome": "failure"}}')
  event=$((cat ./data/authentication.json; echo $failure_overrides; echo $user_overrides) | ./util/deep_merge_json )

  ./util/create_doc "$event"
}
done
